name: Package

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/package.yml"
  workflow_call:
    inputs:
      version:
        description: "Version to build"
        default: "0.0.0"
        required: false
        type: string

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup uv
        if: ${{ inputs.version }}
        uses: astral-sh/setup-uv@v10.2.0

      - name: Change version
        if: ${{ inputs.version }}
        run: uv version ${{ inputs.version }}

      - name: Build Docker Image
        run: docker build -t mixmansion:${{ inputs.version || 'latest' }} .

      - name: Smoke test Docker Image
        run: docker run --rm mixmansion:${{ inputs.version || 'latest' }} --version

      - name: Save Docker Image
        run: docker save mixmansion:${{ inputs.version || 'latest' }} -o mixmansion-${{ inputs.version || 'latest' }}.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v7
        with:
          name: docker-image-${{ inputs.version || 'latest' }}
          path: mixmansion-${{ inputs.version || 'latest' }}.tar
          if-no-files-found: error
